# Generated by Django 6.0.4 on 2026-04-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_reg',
            name='phno',
            field=models.CharField(default='sfdsff', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprov_reg',
            name='phno',
            field=models.CharField(default='default value', max_length=50),
            preserve_default=False,
        ),
    ]
