# Generated by Django 6.0.4 on 2026-04-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0002_customer_reg_phno_serviceprov_reg_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customer_reg',
            name='address',
            field=models.CharField(default='jkfsd', max_length=50),
            preserve_default=False,
        ),
    ]
