# Generated by Django 6.0.4 on 2026-04-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0003_services_customer_reg_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
