# Generated by Django 6.0.4 on 2026-04-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprov_reg',
            name='license',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
