# Generated by Django 6.0.4 on 2026-04-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0005_alter_serviceprov_reg_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_reg',
            name='password',
        ),
        migrations.RemoveField(
            model_name='serviceprov_reg',
            name='password',
        ),
    ]
