# Generated by Django 6.0.4 on 2026-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0006_remove_customer_reg_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='images',
            field=models.FileField(default='sad', max_length=50, upload_to=''),
            preserve_default=False,
        ),
    ]
