# Generated by Django 6.0.4 on 2026-04-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0007_services_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='images',
            new_name='image',
        ),
    ]
