# Generated by Django 6.0.4 on 2026-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0008_rename_images_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprov_reg',
            name='baseprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprov_reg',
            name='servicedetails',
            field=models.CharField(default='f', max_length=500),
            preserve_default=False,
        ),
    ]
