# Generated by Django 6.0.4 on 2026-04-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0009_serviceprov_reg_baseprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('payment', models.CharField(default='pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhoMANApp.customer_reg')),
                ('serviceprov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhoMANApp.serviceprov_reg')),
            ],
        ),
    ]
