# Generated by Django 6.0.4 on 2026-04-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
