# Generated by Django 6.0.4 on 2026-04-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhoMANApp', '0011_booking_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprov_reg',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhoMANApp.services'),
        ),
    ]
